# Super Agent Configuration

# Refer to the official Super Agent documentation at:
# https://buildermethods.com/super-agent

super_agent_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: false

project_types:
  default:
    instructions: ~/.super-agent/instructions
    standards: ~/.super-agent/standards

  # type_a:
  #   instructions: ~/.super-agent/project_types/type_a/instructions
  #   standards: ~/.super-agent/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.super-agent/project_types/type_b/instructions
  #   standards: ~/.super-agent/project_types/type_b/standards

default_project_type: default
